import { prisma } from '../database/prisma'; import { Draft } from '../types/finance'; import { brudam } from '../integrations/brudam'; import { audit } from './AuditService';
const missing=(d:Draft)=>['type','amount','category'].filter(k=>!d[k as keyof Draft]);
export const transactionService={
 missing,
 async saveDraft(userId:string,draft:Draft){ const user=await prisma.user.findUniqueOrThrow({where:{id:userId}}); await prisma.conversationSession.upsert({where:{userId},create:{userId,draft,state:'COLLECTING'},update:{draft,state:'COLLECTING'}}); return user; },
 async createAwaiting(userId:string,draft:Draft,messageId?:string){ if (!Number.isFinite(draft.amount) || draft.amount! <= 0) throw new Error('O valor deve ser positivo e maior que zero.'); const category=await prisma.category.findFirst({where:{name:{equals:draft.category!,mode:'insensitive'},type:draft.type!}}); if(!category) throw new Error('Categoria não cadastrada para este tipo.'); const vehicle=draft.vehicleCode?await prisma.vehicle.findUnique({where:{code:draft.vehicleCode}}):null; const tx=await prisma.transaction.create({data:{type:draft.type!,amount:draft.amount!,categoryId:category.id,description:draft.description||draft.category!,date:new Date(`${draft.date||new Date().toISOString().slice(0,10)}T12:00:00Z`),vehicleId:vehicle?.id, status:'AWAITING_CONFIRMATION',createdById:userId,sourceMessageId:messageId,idempotencyKey:`draft-${userId}-${messageId||Date.now()}`,rawMessage:draft.description}}); await prisma.conversationSession.upsert({where:{userId},create:{userId,draft,transactionId:tx.id,state:'AWAITING_CONFIRMATION'},update:{draft,transactionId:tx.id,state:'AWAITING_CONFIRMATION'}}); await audit('transaction.awaiting_confirmation','transaction',tx.id,userId,tx.id); return tx; },
 async confirm(userId:string){ const session=await prisma.conversationSession.findUnique({where:{userId}}); if(!session?.transactionId) throw new Error('Não há lançamento aguardando confirmação.'); const tx=await prisma.transaction.findUniqueOrThrow({where:{id:session.transactionId}}); if(tx.status!=='AWAITING_CONFIRMATION') throw new Error('Este lançamento não pode ser confirmado.'); const confirmed=await prisma.transaction.update({where:{id:tx.id},data:{status:'CONFIRMED',confirmedById:userId,confirmedAt:new Date()}}); try { const result=await brudam.createTransaction(confirmed); await prisma.transaction.update({where:{id:tx.id},data:{status:'SENT',externalId:result.externalId}}); await audit('transaction.sent','transaction',tx.id,userId,tx.id); } catch { await prisma.transaction.update({where:{id:tx.id},data:{status:'PENDING_SYNC'}}); await audit('transaction.pending_sync','transaction',tx.id,userId,tx.id); } await prisma.conversationSession.delete({where:{userId}}); return tx;
 },
 async cancel(userId:string){ const s=await prisma.conversationSession.findUnique({where:{userId}}); if(s?.transactionId) await prisma.transaction.update({where:{id:s.transactionId},data:{status:'CANCELLED'}}); if(s) await prisma.conversationSession.delete({where:{userId}}); if(s?.transactionId) await audit('transaction.cancelled','transaction',s.transactionId,userId,s.transactionId); },
 async correction(userId:string,field:string,value:string){ const s=await prisma.conversationSession.findUniqueOrThrow({where:{userId}}); const d=s.draft as Draft; const fields:Record<string,keyof Draft>={valor:'amount',tipo:'type',categoria:'category',data:'date',veiculo:'vehicleCode',descrição:'description',descricao:'description',cliente:'customer',fornecedor:'supplier',conta:'account'}; const key=fields[field.toLowerCase()]; if(!key) throw new Error('Campo inválido.'); (d as any)[key]=key==='amount'?Number(value.replace(',','.')):key==='type'?(value.toLowerCase().startsWith('e')?'INCOME':'EXPENSE'):value; await prisma.conversationSession.update({where:{userId},data:{draft:d,state:'COLLECTING'}}); return d; }
};
